[package]
name = "png-msg"
version = "0.1.0"
authors = ["Andres O. Vela <andresovela@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fehler = "1.0.0"
crc = "1.8.1"
